import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <SignedIn>
          <body className={inter.className}>{children}</body>
        </SignedIn>
        <SignedOut>
          <body className={inter.className}>
            <p>Redirecting you to sign in!</p>
            <RedirectToSignIn>
              
            </RedirectToSignIn>
          </body>
        </SignedOut>
      </html>
    </ClerkProvider>
  );
}
